### ISSUE TITLE
Gopkg is out of date

### ISSUE THREAD

**Issue by MaerF0x0** [rafaeljusto/redigomock#24]
The gopkg  v1 points to a version that (afaik) doesnt work.   Possible to add a tag and update gopkg.in ?

**Comment by rafaeljusto** [comment]
Yep! More than a year since the last tag/release. As the library interface changed since v1.0, I increased to version 2.0. Now you can use the import path:

    http://gopkg.in/rafaeljusto/redigomock.v2

Thanks Mike!
