### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by Willyham** [rafaeljusto/redigomock#34]
The latest release (v2.0.0) doesn't contain the new `ExpectSlice` method. Would it be possible to publish a new version which contains this method?

The change set is: https://github.com/rafaeljusto/redigomock/compare/ca49a8af34fc0c903a37409317576da14b3f1cbd...master

If there are no breaking changes in here, then we can publish v2.1.0, otherwise, v3.0.0.

Thanks.

**Comment by rafaeljusto** [comment]
Done! https://github.com/rafaeljusto/redigomock/tree/v2.1

Thanks for reminding me about releases. :smile:

**Comment by Willyham** [comment]
Thanks for the quick turn around!
