### ISSUE TITLE
Problem testing simple non-transactional pipelining 

### ISSUE THREAD

**Issue by davestearns** [rafaeljusto/redigomock#45]
I may be misunderstanding how this package is supposed to work, but I think there might be an issue with how this mock handles simple non-transactional pipelining. I was trying to test some code that uses `redigo/redis` to pipeline two commands: `GET key` followed by `EXPIRE key ttl`. There's no need to do this as a transaction, so the code follows the [simple pipelining example](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Pipelining) in the redigo documentation:

```go
	conn.Send("GET", key)
	conn.Send("EXPIRE", key, ttlDuration.Seconds())
	conn.Flush()

	//GET command reply
	getReply, err := redis.Bytes(conn.Receive())
	if err != nil {
		return fmt.Errorf("error executing GET: %v", err)
	}

        //do something with getReply bytes
```

This seems to work correctly when run against a real redis server. But when I try to test this with the redigomock package, I always get an error when calling `conn.Receive()`, regardless of whether I use `.Expect()` or `.ExpectError()`. The error text is `"no more items"` and it's returned from here: https://github.com/rafaeljusto/redigomock/blob/1d32475ae23cbe2e221e166e452da3279d3dc7bf/redigomock.go#L237

For example, my unit test code looks something like this:

```go
conn := redigomock.NewConn()
conn.Command("GET", key).Expect([]bytes("testing"))
conn.Command("EXPIRE", key, ttlDuration.Seconds()).Expect(1)
if err := callMyFunction(conn); err != nil {
        //this error always occurs
}
```

From what I can see in the code, the mock connection's `.Send()` method adds the commands to `c.queue`:

https://github.com/rafaeljusto/redigomock/blob/1d32475ae23cbe2e221e166e452da3279d3dc7bf/redigomock.go#L195 

But it appears that the `.Flush()` method empties that `c.queue`, calling c.do() for each:

https://github.com/rafaeljusto/redigomock/blob/1d32475ae23cbe2e221e166e452da3279d3dc7bf/redigomock.go#L214

At the top of the `.Receive()` method, the code tests whether `len(c.queue) == 0`, which in this case will always be true, so I always get that `"no more items"` error.

https://github.com/rafaeljusto/redigomock/blob/1d32475ae23cbe2e221e166e452da3279d3dc7bf/redigomock.go#L231

That said, I'm still trying to discern how this package works, so let me know if I've misunderstood something!

**Comment by rafaeljusto** [comment]
@davestearns Check the merged PR from Jakob Green, it should fix your issue. Thanks for spotting this out. 👍

@JakobGreen amazing job with this quick fix! Thanks. 😃
