### ISSUE TITLE
Feature: support for Redis streams

### ISSUE THREAD

**Issue by samisagit** [rafaeljusto/redigomock#49]
I've recently found the need to mock stream responses (which are in a pretty grim format) and it would be great to be able to have a helper function that generated a stream response based on a stream name, messageID, and a map. I've implemented a rudimentary version for my own testing purposes, but it would be nice to have this as part of this mocking lib. Is this in the pipeline? I would be happy to contribute if this is something you think would be useful to people. Otherwise if there is already a nice way of doing this that I've missed could you add it to the documentation?

Thanks in advance!

**Comment by rafaeljusto** [comment]
Hi @samisagit ! Thanks for reaching out. Could you please give an example for this scenario (piece of code would be great) so I could understand it better?

And feel free to contribute to the mock library. 😄
