### ISSUE TITLE
Adding fuzzy argument matching ( like regexes or values in range [-1, 5] for example )

### ISSUE THREAD

**Issue by szank** [rafaeljusto/redigomock#5]
Hi,  I am am passing a time.Now().Unix() as a argument to redis. This means that in the mock I can't provide just a "concrete" value.

I am planning to add fuzzy matching for example : 
intForType := 1 

Command( "some string", 1 , Any { intForType }, Range{ -10.0, 10,0 }, RegexMatch{"[Rr]edigo"}, true)

To make it work the arguments passed to Command and the ones passed to mock connection have to be in the same order. Otherwise everything will just explode when more than one provided regex could match string passed to mock connection for example. 

I am planning to add a new method : FuzzyCommand  which will return a FuzzyCommand struct stored in separate list ( not in the "concrete" command list ).

It is a big change, so I want to check what do you think about it before i submit a pull request :)

Best regards

**Comment by rafaeljusto** [comment]
I usually manage the time.Now() in unit tests using dependency injection or overriding a global function that gives me the current time. But your solution appears to be a cool idea and creates a more flexible mock library. :+1:

**Comment by szank** [comment]
I just committed some code : 
https://github.com/szank/redigomock/tree/add-any-match

For now golint is not complaining and test coverage is 100%. 

This is still WIP, before I create a pull request I will have to add some documentation.  Also, I would like to discuss two things :

1. Shall I move the methods around, or is keeping the "fuzzy" part in separate file OK with you ?
2. If I am allowed to break backward compatibility by making all commands check arguments in order they were provided in conn.Go() func, I could get rid of the distinction between fuzzy and non fuzzy commands.  

Some remarks, for making it easier to read
The current order of maching commands is 
1. Non fuzzy, 
2. Generic command, 
3. Fuzzy command, 

but with fuzzy commands the order they were added does matter
Example:

```Go
Command("HGETALL",NewAnyInt(), 1 ).Expect("someData")
Command("HGETALL",NewAnyInt(),NewAnyInt() ).ExpectError("Error!")
NewConn().Do("HGETALL",1,1)
```
returns something different than 

```Go
Command("HGETALL",NewAnyInt(),NewAnyInt() ).ExpectError("Error!")
Command("HGETALL",NewAnyInt(), 1 ).Expect("someData")
NewConn().Do("HGETALL",1,1)
```

I need to document it all :(

Best regards, 
Maciej

**Comment by rafaeljusto** [comment]
Hi Maciej,

On Tue, Mar 31, 2015 at 8:28 AM, szank <notifications@github.com> wrote:

> I just committed some code :
> https://github.com/szank/redigomock/tree/add-any-match
>
> For now golint is not complaining and test coverage is 100%.
>
> This is still WIP, before I create a pull request I will have to add some
> documentation. Also, I would like to discuss two things :
>
>    1. Shall I move the methods around, or is keeping the "fuzzy" part in
>    separate file OK with you ?
>    2. If I am allowed to break backward compatibility by making all
>    commands check arguments in order they were provided in conn.Go() func, I
>    could get rid of the distinction between fuzzy and non fuzzy commands.
>
> I think we could break the backward compatibility, appears to be a more
elegant approach, I just need to tag the current version and create a
Changelog file to document this.

>
>    1.
>
> Some remarks, for making it easier to read
> The current order of maching commands is
> 1. Non fuzzy,
> 2. Generic command,
> 3. Fuzzy command,
>
> but with fuzzy commands the order they were added does matter
> Example:
>
> Command("HGETALL",NewAnyInt(), 1 ).Expect("someData")Command("HGETALL",NewAnyInt(),NewAnyInt() ).ExpectError("Error!")NewConn().Do("HGETALL",1,1)
>
> returns something different than
>
> Command("HGETALL",NewAnyInt(),NewAnyInt() ).ExpectError("Error!")Command("HGETALL",NewAnyInt(), 1 ).Expect("someData")NewConn().Do("HGETALL",1,1)
>
> I need to document it all :(
>
> Best regards,
> Maciej
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rafaeljusto/redigomock/issues/5#issuecomment-88053464>
> .
>
Cheers!
Rafael
