### ISSUE TITLE
Set gomod-compatible tag

### ISSUE THREAD

**Issue by tetafro** [rafaeljusto/redigomock#55]
Please set gomod-compatible tag (full semver tag - v2.2.0), so that other project can use tag in go.mod. Currently this package is resolved into `github.com/rafaeljusto/redigomock v0.0.0-20190202135759-257e089e14a1`

https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by rafaeljusto** [comment]
👍 Sure thing @tetafro , thanks for reporting this. Created the tag `v2.2.1` with the latest changes:
https://github.com/rafaeljusto/redigomock/tree/v2.2.1
