### ISSUE TITLE
How to simulate slow redis calls?

### ISSUE THREAD

**Issue by rsheasby** [rafaeljusto/redigomock#57]
Hi. Firstly, thanks for this great package. It's really useful.

However, I'm having an issue with trying to create a test case for a long blocking function. In this case I'm doing a BRPOP with a 10 second timeout, then retrying if nothing received (this is to avoid TCP read timeouts). I'm unsure how to mock this though. It seems the conn.Command only allows registering determined responses. Ideally I'd need to test one nil response then a second successful response. I realise I could do Clear() then re-register the command, but this causes a race condition. It would be great would be if we could register a **function** to a command. That gives the flexibility to do all sorts of fun things like responding differently each time, or adding a large delay to the response.

**Comment by rafaeljusto** [comment]
Hey @rsheasby , thanks for reaching out. I don't think you need to sleep for 10 seconds to simulate the desired behaviour. Maybe you could do it using `ExpectError(io.EOF)` on the first call. Check the example below:

### issue57.go

```go
package issues57

import (
	"fmt"
	"io"
	"time"

	"github.com/gomodule/redigo/redis"
)

var pool redis.Pool

// Issues57 investigates PR created at:
// https://github.com/rafaeljusto/redigomock/pull/57
func Issues57() error {
	conn := pool.Get()
	connWithTimeout := conn.(redis.ConnWithTimeout)

	v, err := redis.Int(conn.Do("DEL", "list1", "list2"))
	if err != nil {
		return fmt.Errorf("error executing DEL: %v", err)
	} else if v != 0 {
		return fmt.Errorf("unexpected value returned for DEL: %v", v)
	}

	v, err = redis.Int(conn.Do("RPUSH", "list1", "a", "b", "c"))
	if err != nil {
		return fmt.Errorf("error executing RPUSH: %v", err)
	} else if v != 3 {
		return fmt.Errorf("unexpected value returned for RPUSH: %v", v)
	}

	for retries := 0; retries < 2; retries++ {
		values, err := redis.Strings(connWithTimeout.DoWithTimeout(10*time.Second, "BRPOP", "list1", "list2", "0"))
		switch {
		case err == io.EOF:
			continue
		case err != nil:
			return fmt.Errorf("error executing BRPOP: %v", err)
		case len(values) != 2 || values[0] != "list1" || values[1] != "c":
			return fmt.Errorf("unexpected value returned for BRPOP: %v", values)
		}
	}

	return nil
}
```

### issue57_test.go

```go
package issues57

import (
	"io"
	"testing"

	"github.com/gomodule/redigo/redis"
	"github.com/rafaeljusto/redigomock"
)

func TestIssues57(t *testing.T) {
	tests := []struct {
		name    string
		conn    func(*redigomock.Conn)
		wantErr string
	}{{
		name: "it should execute successfully",
		conn: func(conn *redigomock.Conn) {
			conn.Command("DEL", "list1", "list2").Expect(int64(0))
			conn.Command("RPUSH", "list1", "a", "b", "c").Expect(int64(3))
			conn.Command("BRPOP", "list1", "list2", "0").ExpectError(io.EOF)
			conn.Command("BRPOP", "list1", "list2", "0").Expect([]interface{}{
				[]byte("list1"),
				[]byte("c"),
			})
		},
	}}

	conn := redigomock.NewConn()
	pool = redis.Pool{
		Dial: func() (redis.Conn, error) {
			return conn, nil
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			conn.Clear()
			if tt.conn != nil {
				tt.conn(conn)
			}

			err := Issues57()

			var gotErr string
			if err != nil {
				gotErr = err.Error()
			}
			if gotErr != tt.wantErr {
				t.Errorf("unexpected error '%s'", gotErr)
			}
			if err := conn.ExpectationsWereMet(); err != nil {
				t.Error(err)
			}
		})
	}
}
```

Hope it helps. 🙂

**Comment by rsheasby** [comment]
Ah, that is helpful. I didn't realise you could push a "queue" of responses for the same command. I do still think registering a function would be a useful way of implementing some tests however.

For example, I don't see a way to receive a `PUBLISH`ed message from the test case when you don't already have an expected message ahead of time. There is `GenericCommand`, but I don't see a way to get the arguments that were submitted?

**Comment by rafaeljusto** [comment]
> I do still think registering a function would be a useful way of implementing some tests however.

Maybe you're looking for [GoMock](https://github.com/golang/mock). 🙂  It creates a mock implementation of the desired interface where you can inject the behaviour. Something like:

```go
gomock.InOrder(
  conn.EXPECT().DoWithTimeout(10*time.Second, "BRPOP", "list1", "list2", "0").DoAndReturn(
    func (readTimeout time.Duration, commandName string, args ...interface{}) (reply interface{}, err error) {
      return nil, io.EOF
    },
  ),
  conn.EXPECT().DoWithTimeout(10*time.Second, "BRPOP", "list1", "list2", "0").DoAndReturn(
    func (readTimeout time.Duration, commandName string, args ...interface{}) (reply interface{}, err error) {
      return []interface{}{[]byte("list1"), []byte("c")}, nil
    },
  ),
)
```

> For example, I don't see a way to receive a PUBLISHed message from the test case when you don't already have an expected message ahead of time. There is GenericCommand, but I don't see a way to get the arguments that were submitted?

Not sure if I understood you here. Could you please send me a simplified example of a piece of code that we would need to test?

**Comment by rsheasby** [comment]
I can't really share code but I can try explain better. The function I want to test takes a connection, does some stuff, then publishes the result of the "stuff" via redis. I want the test to basically receive the "stuff" despite not knowing what the value is ahead of time. The test can then validate the "stuff" from other sources of truth.

**Comment by rafaeljusto** [comment]
Thanks for clarifying. Yeah, you're right!

I've created a patch for this, where we would have the `Handle` method for the command. If we decide to merge it you could test it like the following:

### stuff.go
```go
func Stuff(conn redis.ConnWithTimeout) (int64, error) {
	return redis.Int64(conn.Do("PUBLISH", "channel", "stuff"))
}
```

### stuff_test.go
```go
func TestStuff(t *testing.T) {
	conn := redigomock.NewConn()
	conn.GenericCommand("PUBLISH").Handle(redigomock.ResponseHandler(func(args []interface{}) (interface{}, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("unexpected number of arguments: %d", len(args))
		}
		v, ok := args[1].(string)
		if !ok {
			return nil, fmt.Errorf("unexpected type %T", args[1])
		}
		if v != "stuff" {
			return nil, fmt.Errorf("unexpected value '%s'", v)
		}
		return int64(1), nil
	}))

	if _, err := Stuff(conn); err != nil {
		t.Errorf("unexpected error '%v'", err)
	}
	if err := conn.ExpectationsWereMet(); err != nil {
		t.Error(err)
	}
}
```

What do you think?

**Comment by rsheasby** [comment]
That looks perfect! Exactly the sort of thing I'm looking for.

**Comment by rafaeljusto** [comment]
@rsheasby You can find the latest changes on version [v2.4.0](https://github.com/rafaeljusto/redigomock/tree/v2.4.0).
