### ISSUE TITLE
Specify the latest version of redigo as a dependency

### ISSUE THREAD

**Issue by merlinnot** [rafaeljusto/redigomock#63]
An old version of redigo, which was published by accident (not compatible with Go modules) is referenced as a dependency. Seems like we should point to `v1.8.3`?

https://github.com/rafaeljusto/redigomock/blob/9fc97bb99e04c8b1185adf3b403a1dcef82c2ad2/go.mod#L5

**Comment by rafaeljusto** [comment]
Yes! 🤦‍♂️ Sorry about that. Thanks for catching this.

**Comment by rafaeljusto** [comment]
@merlinnot Fix applied to [v3.0.1](https://github.com/rafaeljusto/redigomock/releases/tag/v3.0.1).

**Comment by merlinnot** [comment]
That was quick! :smile:
