### ISSUE TITLE
GPL license - dual licensing possible?

### ISSUE THREAD

**Issue by wgruszczyk** [rafaeljusto/redigomock#70]
In order to use the library in commercial projects a non-viral license would be needed (MIT, Apache-2.0, BSD). Would it be possible to change the license from GPL to non-limiting or provide dual licensing?

I really appreciate any help you can provide.

**Comment by rafaeljusto** [comment]
Hey @wgruszczyk , I've changed it there to MIT, you can go for version `v3.1.2`. 👍  Thanks for raising this.

**Comment by wgruszczyk** [comment]
Hi @rafaeljusto, thank you very much! I appreciate your quick response!
